OpenLiberty/guide-cdi-intro

finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java, finish/src/main/java/io/openliberty/guides/inventory/model/InventoryList.java, finish/src/test/java/it/io/openliberty/guides/inventory/EndpointTest.java
As suggested by YK, and it seems to make sense to have the host changed to system.
=> Changed host to system

README.adoc
will leave comments in line where I should explain the change and we can discuss.
=> guide doc review

README.adoc
I see that this file has already gained ID approval, so please feel free to merge or revert my edit. My reason for this small change is that we don't want to sound like we're accusing the user of something (introducing a bug), so I changed "must" to "might." :) Thanks!
=> Optional ID edit

finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java, finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java, start/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java
=> Fix thread safety issue and inject SystemClient into InventoryManager

.travis.yml
* Update README.adoc
* Update .travis.yml
* Update README.adoc
* Update .travis.yml
* Update .travis.yml
=> Update .travis.yml (#85)

README.adoc, finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java, finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
* Moved SystemClient from InvManager to InvResource in finish
* Initial README change, no updates in hotspot yet
* Updated README
* Updated README
* Updated ordering of manager/systemclient
* Updated README.adoc and copyrights for InventoryManager/Resource
* Removed 2018 from copyright
=> Moving SystemClient to InventoryResource (#84)

README.adoc
Quick fix to address searchability.
=> Add CDI to abstract

README.adoc
update the description for search
=> Qa to master: update the description for search

README.adoc, finish/pom.xml, start/pom.xml
Reduce the SRVE9967W warnings from the messages.log
#96
=> merge qa to master: Updated dependencies

README.adoc, finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java, finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java, finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java
#95 
- Tested with jdk 8&11
- Checked endpoints
- Verified tests
=> Deleted unnecessary imports

README.adoc
Addressing https://github.com/OpenLiberty/guides-common/issues/291
=> Hiding license 

finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java
=> Qa to master: hiding license

finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java
=> Merge qa to master: fixing the hotspot for testUnknownHost()

README.adoc, finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java
- add a hotspot in InventoryResource.java
- update the Readme.adoc
=> Make the instruction more clearer for the tests to detect failure

finish/src/main/java/io/openliberty/guides/inventory/model/SystemData.java, start/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
Issue: https://github.com/openliberty/guides-common/issues/301
=> fixed licensing for SystemData.java

README.adoc, finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java, finish/src/main/java/io/openliberty/guides/inventory/model/SystemData.java, finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java, start/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
=> Merge qa to master: add an hotspot to endpoint and license for SystemData

README.adoc, finish/pom.xml, start/pom.xml
=> Merge qa to master: Update dependencies version

.travis.yml, README.adoc, finish/pom.xml, scripts/travisTest.sh, start/pom.xml
- remove unused dependencies
- addressing https://github.com/OpenLiberty/guides-common/issues/217
- add SEO
- using travisTest.sh (with comments) from template
=> removed unused test dependencies

README.adoc, finish/pom.xml, start/pom.xml
=> Merge qa to master: update Liberty Maven plugin to 3.2

finish/pom.xml, start/pom.xml
Reverts OpenLiberty/guide-cdi-intro#138
=> Revert "Merge qa to master: update Liberty Maven plugin to 3.2"

finish/pom.xml, start/pom.xml
Reverts OpenLiberty/guide-cdi-intro#137
=> Revert "Bump liberty-maven-plugin from 3.1 to 3.2 in /finish"

finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java, finish/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
Updates to error messages made as part of https://github.com/OpenLiberty/guides-common/issues/243
=> Updated error and related tests

README.adoc
Added warning message thrown by test case and explaining that it is expected.
=> Warning message

.github/workflows/test.yml
=> Merge qa to master: explain the warning from the test output

.github/workflows/triggerConversion.yml, README.adoc
=> Merge qa to master: Added workflow trigger for SN automation

.github/workflows/triggerConversion.yml
Changed name of action from `action` to `Rebuild cloud-hosted guide`
=> Changed name of action

.github/workflows/triggerConversion.yml, README.adoc
=> Merge qa to master: allow empty commit to rebuild cloud-hosted guide
